# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890


## Environment Properties

# Read more on this at https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md#apply-parchment-mappings
neogradle.subsystems.parchment.minecraftVersion=1.20.4
neogradle.subsystems.parchment.mappingsVersion=2024.04.14

# The Minecraft version must agree with the NeoForge version to get a valid artifact
minecraft_version=1.20.4
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.20.4]
# The NeoForge version must agree with the Minecraft version to get a valid artifact
neo_version=20.4.251
# The NeoForge version range can use any version of NeoForge as bounds or match the loader version range
neo_version_range=[20.4,)
# The loader version range can only use the major version of Neo/FML as bounds
loader_version_range=[1,)
# Pack version - this changes each minecraft release, in general.
pack_format_number=22


## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=dglabmc
# The human-readable display name for the mod.
mod_name=DG-LAB MC
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=All Rights Reserved
# The mod version. See https://semver.org/
mod_version=1.0.0
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
mod_group_id=dglabmc
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=admilk
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=NeoForge 1.20.4 瀹㈡埛绔?DG-LAB 鎺у埗妯＄粍

