modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
displayTest="IGNORE_SERVER_VERSION"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="\\u0044\\u0047\\u002d\\u004c\\u0041\\u0042 \\u63a7\\u5236\\u4e2d\\u5fc3"
authors="${mod_authors}"
description="""
\\u0046\\u006f\\u0072\\u0067\\u0065 1.15.2 \\u5ba2\\u6237\\u7aef \\u0044\\u0047\\u002d\\u004c\\u0041\\u0042 \\u63a7\\u5236\\u6a21\\u7ec4
"""

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
