forge-1.20.1.enabled=true
forge-1.20.1.loader=forge
forge-1.20.1.minecraft=1.20.1
forge-1.20.1.java=17
forge-1.20.1.path=adapters/forge-1.20.1
neoforge-1.20.2.enabled=true
neoforge-1.20.2.loader=neoforge
neoforge-1.20.2.minecraft=1.20.2
neoforge-1.20.2.java=17
neoforge-1.20.2.path=adapters/neoforge-1.20.2
